// Generated by CoffeeScript 1.8.0
(function() {
  var files, fs, k, v, _fn, _i, _len;

  fs = require('fs');

  files = ['a.txt', 'b.txt', 'c.txt'];

  _fn = function(k) {
    return fs.readFile(v, 'utf-8', function(err, content) {
      if (err) {
        console.log(err);
      }
      return console.log(files[k] + ': ' + content);
    });
  };
  for (k = _i = 0, _len = files.length; _i < _len; k = ++_i) {
    v = files[k];
    _fn(k);
  }

}).call(this);

//# sourceMappingURL=do.js.map
