// Generated by CoffeeScript 1.8.0
(function() {
  var greeting;

  greeting = function(subject) {
    return console.log("hello " + arguments[0]);
  };

  greeting("youqing", "kui");

}).call(this);

//# sourceMappingURL=greeting.js.map
