// Generated by CoffeeScript 1.8.0
(function() {
  var e, odd;

  odd = function(num) {
    if (typeof num === 'number') {
      if (num === Math.round(num)) {
        if (num > 0) {
          return num % 2 === 1;
        } else {
          throw "" + num + " is not a positive";
        }
      } else {
        throw "" + num + " is not a integer";
      }
    } else {
      throw "" + num + " if not a number";
    }
  };

  try {
    console.log(odd(123.123));
  } catch (_error) {
    e = _error;
    console.log(e);
  }

}).call(this);

//# sourceMappingURL=odd.js.map
