// Generated by CoffeeScript 1.8.0
(function() {
  var e, odd;

  odd = function(num) {
    if (typeof num !== 'number') {
      throw "" + num + " is not a number";
    }
    if (num !== Math.round(num)) {
      throw "" + num + " is not a integer";
    }
    if (!(num > 0)) {
      throw "" + num + " is not a positive";
    }
    return num % 2 === 1;
  };

  try {
    console.log(odd("ddd"));
  } catch (_error) {
    e = _error;
    console.log(e);
  }

  (odd(123))();

}).call(this);

//# sourceMappingURL=odd2.js.map
