// Generated by CoffeeScript 1.8.0
(function() {
  var triple, x;

  x = 5;

  triple = function(x) {
    return x *= 3;
  };

  console.log(triple(x));

  console.log(x);

}).call(this);

//# sourceMappingURL=same_name.js.map
