// Generated by CoffeeScript 1.8.0
(function() {
  var age, reincarnate;

  reincarnate = function() {
    var age;
    return age = 0;
  };

  age = 99;

  reincarnate();

  console.log("I am " + age + " years old");

}).call(this);

//# sourceMappingURL=scope2.js.map
