// Generated by CoffeeScript 1.8.0
(function() {
  var age, reincarnate;

  age = 99;

  reincarnate = function() {
    return age = 0;
  };

  reincarnate();

  console.log("I am " + age + " years old");

}).call(this);

//# sourceMappingURL=scope.js.map
