// Generated by CoffeeScript 1.8.0
(function() {
  var reincarnate;

  reincarnate = function() {
    var age;
    return age = 0;
  };

  reincarnate();

  console.log("age = " + age);

}).call(this);

//# sourceMappingURL=scope3.js.map
